from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen



class BaseLLMClient(ABC):
    @abstractmethod
    def generate(self, prompt: str) -> str:
        raise NotImplementedError
    

class MockLLMClient(BaseLLMClient):

    def __init__(self, fixed_answer: str | None = None) -> None:
        self.fixed_answer = fixed_answer
        self.last_prompt: str | None = None

    def generate(self, prompt: str) -> str:

        _validate_prompt(prompt)

        self.last_prompt = prompt

        if self.fixed_answer is not None:
            return self.fixed_answer
        
        return (
            "This is a mock answer generated by MockLLMClient. "
            "The real LLM client has not been connected yet. "
        )
    


class OpenAICompatibleLLMClient(BaseLLMClient):

    def __init__(
        self,
        model_name: str,
        api_key: str | None = None,
        base_url: str | None = None,
        temperature: float = 0.2,
        max_tokens: int = 512,
        timeout: int = 60,
    ) -> None:
        if not isinstance(model_name, str):
            raise TypeError("model_name must be a string")

        if not model_name.strip():
            raise ValueError("model_name must not be empty")

        _validate_temperature(temperature)
        _validate_positive_int(max_tokens, "max_tokens")
        _validate_positive_int(timeout, "timeout")

        self.model_name = model_name
        self.api_key = api_key or os.getenv("LLM_API_KEY")
        self.base_url = (base_url or os.getenv("LLM_BASE_URL") or "https://api.openai.com/v1").rstrip("/")
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.timeout = timeout

        if not self.api_key:
            raise ValueError(
                "API key is missing.Please set LLM_API_KEY environment variable "
                "or pass api_key explicitly."
            )
        
    def generate(self, prompt: str) -> str:
        _validate_prompt(prompt)

        url = f"{self.base_url}/chat/completions"

        payload = {
            "model": self.model_name,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        response_data = self._post_json(url=url, payload=payload)

        try:
            answer = response_data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise ValueError(f"Unexpected LLM API response format: {response_data}") from exc
        
        if not isinstance(answer, str):
            raise TypeError("LLM answer must be a string")

        if not answer.strip():
            raise ValueError("LLM answer is empty")

        return answer.strip()
    
    def _post_json(self, url: str, payload: dict[str, Any]) -> dict[str, Any]:
        data = json.dumps(payload).encode("utf-8")

        request = Request(
            url=url,
            data=data,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
        )

        try:
            with urlopen(request, timeout=self.timeout) as response:
                response_text = response.read().decode("utf-8")
        
        except HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(
                f"LLM API request failed with status {exc.code}: {error_body}"
            ) from exc
        
        except URLError as exc:
            raise RuntimeError(f"LLM API request failed: {exc}") from exc
        
        try:
            response_data = json.loads(response_text)
        except json.JSONDecodeError as exc:
            raise ValueError(f"LLM API returned invalid JSON: {response_text}") from exc
        
        if not isinstance(response_data, dict):
            raise TypeError("LLM API response must be a JSON object")
        
        return response_data
    


def _validate_prompt(prompt: str) -> None:
    """检查 prompt 是否合法。"""
    if not isinstance(prompt, str):
        raise TypeError("prompt must be a string")

    if not prompt.strip():
        raise ValueError("prompt must not be empty")


def _validate_temperature(temperature: float) -> None:
    """检查 temperature 是否合法。"""
    if not isinstance(temperature, (int, float)):
        raise TypeError("temperature must be a number")

    if temperature < 0:
        raise ValueError("temperature must be non-negative")


def _validate_positive_int(value: int, name: str) -> None:
    """检查某个参数是否为正整数。"""
    if not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")

    if value <= 0:
        raise ValueError(f"{name} must be positive")